config/routes.rb
Rails.application.routes.draw do
  resources :beverages
  root 'welcome#index'
  get 'starbucks' => 'welcome#starbucks'
  get 'dunkin' => 'welcome#dunkin'
  
  get 'coffee_showdown' => 'beverages#coffee_showdown'
  post 'results' => 'beverages#results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beverage.rb
class Beverage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beverages_controller.rb
class BeveragesController < ApplicationController
  before_action :set_beverage, only: [:show, :edit, :update, :destroy]

  # GET /beverages
  # GET /beverages.json
  def index
    @beverages = Beverage.all
  end

  # GET /beverages/1
  # GET /beverages/1.json
  def show
  end

  # GET /beverages/new
  def new
    @beverage = Beverage.new
  end

  # GET /beverages/1/edit
  def edit
  end

  # POST /beverages
  # POST /beverages.json
  def create
    @beverage = Beverage.new(beverage_params)

    respond_to do |format|
      if @beverage.save
        format.html { redirect_to @beverage, notice: 'Beverage was successfully created.' }
        format.json { render :show, status: :created, location: @beverage }
      else
        format.html { render :new }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beverages/1
  # PATCH/PUT /beverages/1.json
  def update
    respond_to do |format|
      if @beverage.update(beverage_params)
        format.html { redirect_to @beverage, notice: 'Beverage was successfully updated.' }
        format.json { render :show, status: :ok, location: @beverage }
      else
        format.html { render :edit }
        format.json { render json: @beverage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beverages/1
  # DELETE /beverages/1.json
  def destroy
    @beverage.destroy
    respond_to do |format|
      format.html { redirect_to beverages_url, notice: 'Beverage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def coffee_showdown
    @beverages = Beverage.all

    @drinks = Beverage.pluck(:name).sort.uniq
  end

  def results
    @beverages = Beverage.where(name: params[:name])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beverage
      @beverage = Beverage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beverage_params
      params.require(:beverage).permit(:brand, :name, :price, :caffeine, :calories)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def starbucks
  end

  def dunkin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beverages_helper.rb
module BeveragesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beverages/_form.html.erb
<%= form_with(model: beverage, local: true) do |form| %>
  <% if beverage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beverage.errors.count, "error") %> prohibited this beverage from being saved:</h2>

      <ul>
      <% beverage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :caffeine %>
    <%= form.number_field :caffeine, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :calories %>
    <%= form.number_field :calories, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/beverages/coffee_showdown.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-header">Dunkin' vs Starbucks - a costly decision</h1>

<div class="row">
  <div class="well col-md-5">
    <h2>Dunkin'</h2>
      <table class="table">
        <tr>
          <th>Beverage</th>
          <th>Price</th>
          <th>Caffeine</th>
          <th>Calories</th>
        </tr>
        <% @beverages.each do |beverage| %>
          <% if beverage.brand == 'Dunkin' %>
            <tr>
              <td><%= beverage.name %></td>
              <td><%= number_to_currency beverage.price %></td>
              <td><%= beverage.caffeine %>mg</td>
              <td><%= beverage.calories %></td>
            </tr>
          <% end %>
        <% end %>
      </table>

    <p>*based on Medium sized coffee - 16oz (cold - 24oz)</p>
  </div>

  <div class="col-md-2">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Click Here to Begin</button>
  </div>

  <div class="well col-md-5">
    <h2>Starbucks</h2>
      <table class="table">
        <tr>
          <th>Beverage</th>
          <th>Price</th>
          <th>Caffeine</th>
          <th>Calories</th>
        </tr>
        <% @beverages.each do |beverage| %>
          <% if beverage.brand == 'Starbucks' %>
            <tr>
              <td><%= beverage.name %></td>
              <td><%= number_to_currency beverage.price %></td>
              <td><%= beverage.caffeine %>mg</td>
              <td><%= beverage.calories %></td>
            </tr>
          <% end %>
        <% end %>
      </table>

    <p>*based on Grande sized coffee - 16oz</p>
  </div>

</div>


<!-- Modal Code -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Select a drink</h3>
      </div>

      <div class="row modal-body">
        <%= form_with url: results_path, local: true do |form| %>
          <%= form.select :name, @drinks.collect {|c| [c, c] }, {include_blank: "Please select a drink"}, class: "form-control" %>
          <%= form.submit "submit", class: "btn btn-primary" %>
        <% end %>
      </div>
        
    </div>
  </div>
</div>

app/views/beverages/edit.html.erb
<h1>Editing Beverage</h1>

<%= render 'form', beverage: @beverage %>

<%= link_to 'Show', @beverage %> |
<%= link_to 'Back', beverages_path %>

app/views/beverages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Beverages</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Beverage</th>
      <th>Price</th>
      <th>Caffeine</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beverages.each do |beverage| %>
      <tr>
        <td><%= beverage.brand %></td>
        <td><%= beverage.name %></td>
        <td><%= beverage.price %></td>
        <td><%= beverage.caffeine %></td>
        <td><%= beverage.calories %></td>
        <td><%= link_to 'Show', beverage %></td>
        <td><%= link_to 'Edit', edit_beverage_path(beverage) %></td>
        <td><%= link_to 'Destroy', beverage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beverage', new_beverage_path %>

app/views/beverages/new.html.erb
<h1>New Beverage</h1>

<%= render 'form', beverage: @beverage %>

<%= link_to 'Back', beverages_path %>

app/views/beverages/results.html.erb
<h1>Results</h1>

<h2>Per Day</h2>
  <table class="table">
    <tr>
      <th>Store</th>
      <th>Drink</th>
      <th>Price</th>
      <th>Caffeine</th>
      <th>Calories</th>
    </tr>
    <% @beverages.each do |beverage| %>
      <tr>
        <td><%= beverage.brand %></td>
        <td><%= beverage.name %></td>
        <td><%= number_to_currency beverage.price %></td>
        <td><%= beverage.caffeine %>mg</td>
        <td><%= beverage.calories %></td>
      </tr>
    <% end %>
  </table>

<h2>Per Week</h2>
  <table class="table">
    <tr>
      <th>Store</th>
      <th>Drink</th>
      <th>Price</th>
      <th>Caffeine</th>
      <th>Calories</th>
    </tr>
    <tr>
      <% @beverages.each do |beverage| %>
        <tr>
          <td><%= beverage.brand %></td>
          <td><%= beverage.name %></td>
          <td><%= number_to_currency beverage.price * 7 %></td>
          <td><%= beverage.caffeine * 7 %>mg</td>
          <td><%= beverage.calories * 7 %></td>
        </tr>
      <% end %>
    </tr>
  </table>

<h2>Per Month</h2>
  <table class="table">
    <tr>
      <th>Store</th>
      <th>Drink</th>
      <th>Price</th>
      <th>Caffeine</th>
      <th>Calories</th>
    </tr>
    <tr>
      <% @beverages.each do |beverage| %>
        <tr>
          <td><%= beverage.brand %></td>
          <td><%= beverage.name %></td>
          <td><%= number_to_currency beverage.price * 30 %></td>
          <td><%= beverage.caffeine * 30 %>mg</td>
          <td><%= beverage.calories * 30 %></td>
        </tr>
      <% end %>
    </tr>
  </table>

<h2>Per Year</h2>
  <table class="table">
    <tr>
      <th>Store</th>
      <th>Drink</th>
      <th>Price</th>
      <th>Caffeine</th>
      <th>Calories</th>
    </tr>
    <tr>
      <% @beverages.each do |beverage| %>
        <tr>
          <td><%= beverage.brand %></td>
          <td><%= beverage.name %></td>
          <td><%= number_to_currency beverage.price * 365 %></td>
          <td><%= beverage.caffeine * 365 %>mg</td>
          <td><%= beverage.calories * 365 %></td>
        </tr>
      <% end %>
    </tr>
  </table>

app/views/beverages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @beverage.brand %>
</p>

<p>
  <strong>Beverage:</strong>
  <%= @beverage.beverage %>
</p>

<p>
  <strong>Price:</strong>
  <%= @beverage.price %>
</p>

<p>
  <strong>Caffeine:</strong>
  <%= @beverage.caffeine %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @beverage.calories %>
</p>

<%= link_to 'Edit', edit_beverage_path(@beverage) %> |
<%= link_to 'Back', beverages_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><%= link_to "Final Project", root_path, class: "navbar-brand" %></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Dunkin'", dunkin_path, class: "btn" %></li>
        <li><%= link_to "Starbucks", starbucks_path, class: "btn" %></li>
        <li><%= link_to "Coffee Showdown", coffee_showdown_path, class: "btn" %></li>
      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeAnalysis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/dunkin.html.erb
<h1 class="page-header">About Dunkin'</h1>

<div class="row">

  <div class="col-md-3">
    <img src="https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/Dunkin%27_Donuts_logo.svg/220px-Dunkin%27_Donuts_logo.svg.png"><br><br>

    <img class="img-responsive" src="https://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2018/01/16/104948374-1_4_Cropped.1910x1000.jpg">
  </div>

  <div class="col-md-9 well">
    <p>Dunkin' Donuts, rebranding as Dunkin' (and also known colloquially as Dunkies, Dunkins, and Dunk[3]) is an American multinational quick service restaurant chain based in Canton, Massachusetts. It was founded in 1950 by William Rosenberg in Quincy, Massachusetts, and is one of the largest coffee and baked goods chains in the world, with more than 12,000 restaurants in 36 countries.[4][5] The chain's products include donuts, bagels, other baked goods, and a variety of hot and iced beverages.[6] The chain is currently owned by Dunkin' Brands.</p>

    <p>In 1990, Dunkin' Donuts acquired its main competitor, Mister Donut; the chain's North American locations were largely converted to Dunkin' Donuts, although the brand maintains presences in international markets.[7] In September 2018 the company announced plans to change its name to just Dunkin', effective January 2019.[8]</p>
  </div>

</div>

app/views/welcome/index.html.erb
<h1 class="page-header">My Final Project</h1>

<div class="well">
  <p>For my final project, I will be creating a web app that will analyze your spending habits at 2 of your favorite coffee joints - Starbucks and Dunkin'.  The purpose is to show how much money you spend at a particular store, and to make a recommendation that will save you $$$!</p>

  <p>The analysis will also compare the nutrition benefits (i.e. caffeine and calories) and show how much more (or less) you are consuming at a particular store.</p>

  <p>Click on the Nav Bar tabs to learn more about Dunkin' and Starbucks and their history, or click on the Coffee Showdown tab to start the analysis.</p>
</div>

app/views/welcome/starbucks.html.erb
<h1 class="page-header">About Starbucks</h1>

<div class="row">

  <div class="col-md-3">
    <img src="https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/175px-Starbucks_Corporation_Logo_2011.svg.png"><br><br>

    <img class="img-responsive" src="https://nails.newsela.com/s3/newsela-media/article_media/2018/07/Starbucks-to-open-first-sign-language-store-18c633d7.jpg?crop=0%2C83%2C1600%2C983&height=497&width=885">
  </div>

  <div class="col-md-9 well">
    <p>Starbucks Corporation is an American coffee company and coffeehouse chain. Starbucks was founded in Seattle, Washington in 1971. As of 2018, the company operates 28,218[2] locations worldwide.</p>

    <p>Starbucks is considered the main representative of "second wave coffee", initially distinguishing itself from other coffee-serving venues in the US by taste, quality, and customer experience while popularizing darkly roasted coffee.[5] Since the 2000s, third wave coffee makers have targeted quality-minded coffee drinkers with hand-made coffee based on lighter roasts, while Starbucks nowadays uses automated espresso machines for efficiency and safety reasons.[5][6]</p>

    <p>Starbucks locations serve hot and cold drinks, whole-bean coffee, microground instant coffee known as VIA, espresso, caffe latte, full- and loose-leaf teas including Teavana tea products,[7] Evolution Fresh juices, Frappuccino beverages, La Boulange pastries, and snacks including items such as chips and crackers; some offerings (including their annual fall launch of the Pumpkin Spice Latte) are seasonal or specific to the locality of the store. Many stores sell pre-packaged food items, hot and cold sandwiches, and drinkware including mugs and tumblers; select "Starbucks Evenings" locations offer beer, wine, and appetizers.[8] Starbucks-brand coffee, ice cream, and bottled cold coffee drinks are also sold at grocery stores.</p>

    <p>Starbucks first became profitable in Seattle in the early 1980s.[9] Despite an initial economic downturn with its expansion into the Midwest and British Columbia in the late 1980s,[10] the company experienced revitalized prosperity with its entry into California in the early 1990s.[11] The first Starbucks location outside North America opened in Tokyo in 1996; overseas properties now constitute almost one-third of its stores.[12] The company opened an average of two new locations daily between 1987 and 2007.[13]</p>

    <p>On December 1, 2016, Howard Schultz announced he would resign as CEO effective April 2017 and would be replaced by Kevin Johnson. Johnson assumed the role of CEO on April 3, 2017,[14] and Howard Schultz retired to become Chairman Emeritus effective June 26, 2018.[15]</p>
  </div>

</div>